### ISSUE TITLE
[Bug] game crash

### ISSUE THREAD

**Issue by vocaloidkiss** [Hendrix-Shen/MagicLib#95] opened 2024-08-24 13:17 UTC
### Minecraft Version

JAVA fabric loader0.16.2 1.21

### MagicLib Version

MasaGadget-mc1.21-fabric-4.0.364-stable

### Description

 crash when i load some chunks with no reason

### To Reproduce

 crash when i load some chunks with no reason（i dk

### Log

[crash-2024-08-24_21.11.07-client.txt](https://github.com/user-attachments/files/16736763/crash-2024-08-24_21.11.07-client.txt)

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by vocaloidkiss** [comment] 2024-08-24 13:19
MagicLib-mc1.21.0-fabric-0.8.596-beta

**Comment by Hendrix-Shen** [comment] 2024-08-24 13:27
Duplicate of #90

**Closed as not planned by Hendrix-Shen** 2024-08-24 13:27 UTC
Labels: type: bug, resolution: duplicate
